<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationTemplatesSeeder extends Seeder
{
    /**
     * Seed the notification templates with all 70+ enterprise notification types.
     */
    public function run(): void
    {
        $templates = [
            // ==================== ORDER & DELIVERY (16 types) ====================
            [
                'code' => 'order_placed',
                'category' => 'order',
                'priority' => 'high',
                'title' => '✅ Order Placed Successfully',
                'title_ar' => '✅ تم تقديم الطلب بنجاح',
                'message' => 'Your order #{order_number} has been placed. We\'ll confirm it shortly.',
                'message_ar' => 'تم تقديم طلبك رقم #{order_number}. سنؤكده قريباً.',
                'icon' => '✅',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'total']),
            ],
            [
                'code' => 'order_confirmed',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🎉 Order Confirmed',
                'title_ar' => '🎉 تم تأكيد الطلب',
                'message' => 'Great news! Your order #{order_number} has been confirmed.',
                'message_ar' => 'أخبار رائعة! تم تأكيد طلبك رقم #{order_number}.',
                'icon' => '🎉',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id']),
            ],
            [
                'code' => 'order_preparing',
                'category' => 'order',
                'priority' => 'medium',
                'title' => '👨‍🍳 Preparing Your Order',
                'title_ar' => '👨‍🍳 جاري تحضير طلبك',
                'message' => 'Your order #{order_number} is being prepared with care.',
                'message_ar' => 'جاري تحضير طلبك رقم #{order_number} بعناية.',
                'icon' => '👨‍🍳',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id']),
            ],
            [
                'code' => 'order_cancelled_store',
                'category' => 'order',
                'priority' => 'critical',
                'title' => '❌ Order Cancelled',
                'title_ar' => '❌ تم إلغاء الطلب',
                'message' => 'Unfortunately, your order #{order_number} has been cancelled. Reason: {reason}',
                'message_ar' => 'للأسف، تم إلغاء طلبك رقم #{order_number}. السبب: {reason}',
                'icon' => '❌',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'reason']),
            ],
            [
                'code' => 'order_modified',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🔄 Order Modified',
                'title_ar' => '🔄 تم تعديل الطلب',
                'message' => 'Your order #{order_number} has been modified. New total: {total} EGP',
                'message_ar' => 'تم تعديل طلبك رقم #{order_number}. الإجمالي الجديد: {total} جنيه',
                'icon' => '🔄',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'total', 'changes']),
            ],
            [
                'code' => 'payment_failed',
                'category' => 'order',
                'priority' => 'critical',
                'title' => '💳 Payment Failed',
                'title_ar' => '💳 فشل الدفع',
                'message' => 'Payment for order #{order_number} failed. Please try again.',
                'message_ar' => 'فشل دفع الطلب رقم #{order_number}. يرجى المحاولة مرة أخرى.',
                'icon' => '💳',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id']),
            ],
            [
                'code' => 'payment_successful',
                'category' => 'order',
                'priority' => 'high',
                'title' => '💳 Payment Successful',
                'title_ar' => '💳 تم الدفع بنجاح',
                'message' => 'Payment of {amount} EGP for order #{order_number} was successful.',
                'message_ar' => 'تم دفع {amount} جنيه للطلب رقم #{order_number} بنجاح.',
                'icon' => '💳',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'amount']),
            ],
            [
                'code' => 'out_for_delivery',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🚚 Out for Delivery',
                'title_ar' => '🚚 في الطريق إليك',
                'message' => 'Your order #{order_number} is on its way! ETA: {eta}',
                'message_ar' => 'طلبك رقم #{order_number} في الطريق! الوصول المتوقع: {eta}',
                'icon' => '🚚',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'eta', 'driver_name']),
            ],
            [
                'code' => 'courier_nearby',
                'category' => 'order',
                'priority' => 'high',
                'title' => '📍 Courier is Nearby',
                'title_ar' => '📍 المندوب قريب منك',
                'message' => 'Your delivery for order #{order_number} is almost there! {distance} away.',
                'message_ar' => 'توصيل طلبك رقم #{order_number} على وشك الوصول! يبعد {distance}.',
                'icon' => '📍',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'distance']),
            ],
            [
                'code' => 'delivery_delayed',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🕒 Delivery Delayed',
                'title_ar' => '🕒 تأخر التوصيل',
                'message' => 'Sorry! Your order #{order_number} is delayed. New ETA: {new_eta}',
                'message_ar' => 'عذراً! تأخر طلبك رقم #{order_number}. الوقت الجديد: {new_eta}',
                'icon' => '🕒',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'new_eta', 'reason']),
            ],
            [
                'code' => 'order_delivered',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🏁 Order Delivered',
                'title_ar' => '🏁 تم التوصيل',
                'message' => 'Your order #{order_number} has been delivered. Enjoy! 🎉',
                'message_ar' => 'تم توصيل طلبك رقم #{order_number}. بالهنا والشفا! 🎉',
                'icon' => '🏁',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id']),
            ],
            [
                'code' => 'delivery_failed',
                'category' => 'order',
                'priority' => 'critical',
                'title' => '❌ Delivery Failed',
                'title_ar' => '❌ فشل التوصيل',
                'message' => 'We couldn\'t deliver order #{order_number}. Reason: {reason}',
                'message_ar' => 'لم نتمكن من توصيل الطلب رقم #{order_number}. السبب: {reason}',
                'icon' => '❌',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'reason']),
            ],
            [
                'code' => 'order_returned',
                'category' => 'order',
                'priority' => 'high',
                'title' => '🔁 Order Returned',
                'title_ar' => '🔁 تم إرجاع الطلب',
                'message' => 'Your return for order #{order_number} has been received.',
                'message_ar' => 'تم استلام إرجاع طلبك رقم #{order_number}.',
                'icon' => '🔁',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id']),
            ],
            [
                'code' => 'refund_initiated',
                'category' => 'order',
                'priority' => 'high',
                'title' => '💰 Refund Initiated',
                'title_ar' => '💰 بدأ استرداد المبلغ',
                'message' => 'Refund of {amount} EGP for order #{order_number} is being processed.',
                'message_ar' => 'جاري معالجة استرداد {amount} جنيه للطلب رقم #{order_number}.',
                'icon' => '💰',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'amount']),
            ],
            [
                'code' => 'refund_completed',
                'category' => 'order',
                'priority' => 'high',
                'title' => '💰 Refund Completed',
                'title_ar' => '💰 تم الاسترداد',
                'message' => '{amount} EGP has been refunded to your wallet for order #{order_number}.',
                'message_ar' => 'تم استرداد {amount} جنيه إلى محفظتك للطلب رقم #{order_number}.',
                'icon' => '💰',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['order_number', 'order_id', 'amount']),
            ],
            [
                'code' => 'invoice_ready',
                'category' => 'order',
                'priority' => 'low',
                'title' => '📄 Invoice Ready',
                'title_ar' => '📄 الفاتورة جاهزة',
                'message' => 'Your invoice for order #{order_number} is ready to download.',
                'message_ar' => 'فاتورتك للطلب رقم #{order_number} جاهزة للتحميل.',
                'icon' => '📄',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_number', 'order_id', 'invoice_url']),
            ],

            // ==================== PRODUCT & INVENTORY (6 types) ====================
            [
                'code' => 'product_back_in_stock',
                'category' => 'product',
                'priority' => 'medium',
                'title' => '📦 Back in Stock!',
                'title_ar' => '📦 متوفر الآن!',
                'message' => '{product_name} is back in stock. Get it before it\'s gone!',
                'message_ar' => '{product_name} متوفر الآن. اطلبه قبل نفاذه!',
                'icon' => '📦',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'product_image']),
            ],
            [
                'code' => 'product_out_of_stock_cart',
                'category' => 'product',
                'priority' => 'high',
                'title' => '❌ Item Out of Stock',
                'title_ar' => '❌ المنتج غير متوفر',
                'message' => '{product_name} in your cart is now out of stock.',
                'message_ar' => '{product_name} في سلتك غير متوفر حالياً.',
                'icon' => '❌',
                'default_action_target' => '/cart',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'product_low_stock',
                'category' => 'product',
                'priority' => 'medium',
                'title' => '⚠️ Low Stock Alert',
                'title_ar' => '⚠️ تنبيه نفاذ الكمية',
                'message' => 'Only {quantity} left of {product_name}. Order now!',
                'message_ar' => 'متبقي {quantity} فقط من {product_name}. اطلب الآن!',
                'icon' => '⚠️',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'quantity']),
            ],
            [
                'code' => 'new_product_category',
                'category' => 'product',
                'priority' => 'low',
                'title' => '🆕 New Product Alert',
                'title_ar' => '🆕 منتج جديد',
                'message' => 'New {product_name} added to {category_name}!',
                'message_ar' => 'تم إضافة {product_name} جديد في {category_name}!',
                'icon' => '🆕',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'category_name']),
            ],
            [
                'code' => 'product_price_changed',
                'category' => 'product',
                'priority' => 'medium',
                'title' => '💸 Price Drop!',
                'title_ar' => '💸 انخفاض السعر!',
                'message' => '{product_name} dropped from {old_price} to {new_price} EGP!',
                'message_ar' => 'انخفض سعر {product_name} من {old_price} إلى {new_price} جنيه!',
                'icon' => '💸',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'old_price', 'new_price']),
            ],
            [
                'code' => 'product_discontinued',
                'category' => 'product',
                'priority' => 'medium',
                'title' => '🛑 Product Discontinued',
                'title_ar' => '🛑 تم إيقاف المنتج',
                'message' => '{product_name} has been discontinued. Check similar products.',
                'message_ar' => 'تم إيقاف {product_name}. تصفح منتجات مشابهة.',
                'icon' => '🛑',
                'default_action_target' => '/category/{category_id}',
                'variables' => json_encode(['product_name', 'product_id', 'category_id']),
            ],

            // ==================== OFFERS & PROMOTIONS (11 types) ====================
            [
                'code' => 'new_offer',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🎉 New Offer Available',
                'title_ar' => '🎉 عرض جديد متاح',
                'message' => '{offer_title} - Save up to {discount}%!',
                'message_ar' => '{offer_title} - وفر حتى {discount}%!',
                'icon' => '🎉',
                'default_action_target' => '/offers/{offer_id}',
                'variables' => json_encode(['offer_title', 'offer_id', 'discount']),
            ],
            [
                'code' => 'flash_sale_started',
                'category' => 'promo',
                'priority' => 'high',
                'title' => '⏰ Flash Sale Started!',
                'title_ar' => '⏰ بدأ التخفيض السريع!',
                'message' => '🔥 {sale_title} is LIVE! Up to {discount}% off. Ends in {hours} hours!',
                'message_ar' => '🔥 {sale_title} بدأ الآن! خصم حتى {discount}%. ينتهي خلال {hours} ساعات!',
                'icon' => '⏰',
                'default_action_target' => '/flash-sale/{sale_id}',
                'variables' => json_encode(['sale_title', 'sale_id', 'discount', 'hours']),
            ],
            [
                'code' => 'flash_sale_ending',
                'category' => 'promo',
                'priority' => 'high',
                'title' => '⏰ Flash Sale Ending Soon!',
                'title_ar' => '⏰ التخفيض على وشك الانتهاء!',
                'message' => '⚡ Only {minutes} minutes left for {sale_title}! Don\'t miss out!',
                'message_ar' => '⚡ متبقي {minutes} دقيقة فقط على {sale_title}! لا تفوت الفرصة!',
                'icon' => '⏰',
                'default_action_target' => '/flash-sale/{sale_id}',
                'variables' => json_encode(['sale_title', 'sale_id', 'minutes']),
            ],
            [
                'code' => 'limited_time_deal',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🔥 Limited Time Deal',
                'title_ar' => '🔥 عرض لفترة محدودة',
                'message' => '{product_name} at {price} EGP - Today only!',
                'message_ar' => '{product_name} بسعر {price} جنيه - اليوم فقط!',
                'icon' => '🔥',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'price']),
            ],
            [
                'code' => 'buy_one_get_one',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🎁 Buy 1 Get 1 FREE!',
                'title_ar' => '🎁 اشتري 1 واحصل على 1 مجاناً!',
                'message' => 'BOGO deal on {product_name}! Limited time only.',
                'message_ar' => 'عرض اشتري واحد واحصل على واحد مجاناً على {product_name}!',
                'icon' => '🎁',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'price_drop_watched',
                'category' => 'promo',
                'priority' => 'high',
                'title' => '💸 Price Drop on Your Watchlist',
                'title_ar' => '💸 انخفاض سعر منتج تتابعه',
                'message' => '{product_name} dropped to {new_price} EGP (was {old_price})!',
                'message_ar' => 'انخفض {product_name} إلى {new_price} جنيه (كان {old_price})!',
                'icon' => '💸',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'old_price', 'new_price']),
            ],
            [
                'code' => 'coupon_available',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🧾 New Coupon for You!',
                'title_ar' => '🧾 كوبون جديد لك!',
                'message' => 'Use code {code} for {discount} off! Valid until {expires}.',
                'message_ar' => 'استخدم الكود {code} واحصل على خصم {discount}! صالح حتى {expires}.',
                'icon' => '🧾',
                'default_action_target' => '/offers',
                'variables' => json_encode(['code', 'discount', 'expires']),
            ],
            [
                'code' => 'coupon_expiring',
                'category' => 'promo',
                'priority' => 'high',
                'title' => '🧾 Coupon Expiring Soon!',
                'title_ar' => '🧾 الكوبون على وشك الانتهاء!',
                'message' => 'Your coupon {code} expires in {hours} hours! Use it now.',
                'message_ar' => 'كوبونك {code} ينتهي خلال {hours} ساعات! استخدمه الآن.',
                'icon' => '🧾',
                'default_action_target' => '/offers',
                'variables' => json_encode(['code', 'hours']),
            ],
            [
                'code' => 'coupon_expired',
                'category' => 'promo',
                'priority' => 'low',
                'title' => '❌ Coupon Expired',
                'title_ar' => '❌ انتهى الكوبون',
                'message' => 'Your coupon {code} has expired. Check our new offers!',
                'message_ar' => 'انتهى كوبونك {code}. تصفح عروضنا الجديدة!',
                'icon' => '❌',
                'default_action_target' => '/offers',
                'variables' => json_encode(['code']),
            ],
            [
                'code' => 'loyalty_reward',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🥇 Loyalty Reward Unlocked!',
                'title_ar' => '🥇 مكافأة الولاء!',
                'message' => 'You\'ve earned {points} points! Redeem for {reward}.',
                'message_ar' => 'حصلت على {points} نقطة! استبدلها بـ {reward}.',
                'icon' => '🥇',
                'default_action_target' => '/profile/rewards',
                'variables' => json_encode(['points', 'reward']),
            ],
            [
                'code' => 'personalized_offer',
                'category' => 'promo',
                'priority' => 'medium',
                'title' => '🎯 Special Offer Just for You',
                'title_ar' => '🎯 عرض خاص لك',
                'message' => 'Based on your preferences: {offer_description}',
                'message_ar' => 'بناءً على تفضيلاتك: {offer_description}',
                'icon' => '🎯',
                'default_action_target' => '/offers/{offer_id}',
                'variables' => json_encode(['offer_description', 'offer_id']),
            ],

            // ==================== CART & CHECKOUT (7 types) ====================
            [
                'code' => 'cart_item_removed_stock',
                'category' => 'cart',
                'priority' => 'high',
                'title' => '🛒 Item Removed from Cart',
                'title_ar' => '🛒 تم حذف منتج من السلة',
                'message' => '{product_name} was removed because it\'s out of stock.',
                'message_ar' => 'تم حذف {product_name} لأنه غير متوفر.',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'cart_price_changed',
                'category' => 'cart',
                'priority' => 'medium',
                'title' => '🛒 Price Changed in Cart',
                'title_ar' => '🛒 تغير سعر في السلة',
                'message' => '{product_name} price changed from {old_price} to {new_price} EGP.',
                'message_ar' => 'تغير سعر {product_name} من {old_price} إلى {new_price} جنيه.',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['product_name', 'old_price', 'new_price']),
            ],
            [
                'code' => 'cart_abandoned_1h',
                'category' => 'cart',
                'priority' => 'medium',
                'title' => '🛒 Forgot Something?',
                'title_ar' => '🛒 نسيت شيئاً؟',
                'message' => 'You have {count} items worth {total} EGP in your cart!',
                'message_ar' => 'لديك {count} منتجات بقيمة {total} جنيه في سلتك!',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['count', 'total']),
            ],
            [
                'code' => 'cart_abandoned_24h',
                'category' => 'cart',
                'priority' => 'medium',
                'title' => '🛒 Your Cart Misses You!',
                'title_ar' => '🛒 سلتك تنتظرك!',
                'message' => 'Complete your order of {count} items. Some may sell out!',
                'message_ar' => 'أكمل طلبك من {count} منتجات. قد ينفد بعضها!',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['count', 'total']),
            ],
            [
                'code' => 'cart_item_restocked',
                'category' => 'cart',
                'priority' => 'high',
                'title' => '🛒 Cart Item Back in Stock!',
                'title_ar' => '🛒 منتج السلة متوفر الآن!',
                'message' => '{product_name} is back! Complete your order now.',
                'message_ar' => '{product_name} متوفر الآن! أكمل طلبك.',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'minimum_order_warning',
                'category' => 'cart',
                'priority' => 'medium',
                'title' => '🛒 Minimum Order Not Met',
                'title_ar' => '🛒 لم يتحقق الحد الأدنى',
                'message' => 'Add {amount} EGP more to reach minimum order of {minimum} EGP.',
                'message_ar' => 'أضف {amount} جنيه للوصول للحد الأدنى {minimum} جنيه.',
                'icon' => '🛒',
                'default_action_target' => '/cart',
                'variables' => json_encode(['amount', 'minimum']),
            ],
            [
                'code' => 'free_delivery_unlocked',
                'category' => 'cart',
                'priority' => 'medium',
                'title' => '🎉 Free Delivery Unlocked!',
                'title_ar' => '🎉 حصلت على توصيل مجاني!',
                'message' => 'Your order qualifies for FREE delivery!',
                'message_ar' => 'طلبك مؤهل للتوصيل المجاني!',
                'icon' => '🎉',
                'default_action_target' => '/cart',
                'variables' => json_encode([]),
            ],

            // ==================== CHAT & SUPPORT (6 types) ====================
            [
                'code' => 'new_support_message',
                'category' => 'chat',
                'priority' => 'high',
                'title' => '💬 New Support Message',
                'title_ar' => '💬 رسالة دعم جديدة',
                'message' => 'You have a new message from support.',
                'message_ar' => 'لديك رسالة جديدة من الدعم.',
                'icon' => '💬',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['complaint_id', 'ticket_number']),
            ],
            [
                'code' => 'agent_joined_chat',
                'category' => 'chat',
                'priority' => 'medium',
                'title' => '💬 Agent Joined',
                'title_ar' => '💬 انضم موظف الدعم',
                'message' => '{agent_name} has joined the conversation.',
                'message_ar' => 'انضم {agent_name} للمحادثة.',
                'icon' => '💬',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['agent_name', 'complaint_id']),
            ],
            [
                'code' => 'chat_escalated',
                'category' => 'chat',
                'priority' => 'high',
                'title' => '💬 Chat Escalated',
                'title_ar' => '💬 تم تصعيد المحادثة',
                'message' => 'Your issue #{ticket_number} has been escalated to a supervisor.',
                'message_ar' => 'تم تصعيد مشكلتك رقم #{ticket_number} للمشرف.',
                'icon' => '💬',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['ticket_number', 'complaint_id']),
            ],
            [
                'code' => 'support_ticket_updated',
                'category' => 'chat',
                'priority' => 'medium',
                'title' => '💬 Ticket Updated',
                'title_ar' => '💬 تم تحديث التذكرة',
                'message' => 'Your support ticket #{ticket_number} status: {status}',
                'message_ar' => 'حالة تذكرتك رقم #{ticket_number}: {status}',
                'icon' => '💬',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['ticket_number', 'complaint_id', 'status']),
            ],
            [
                'code' => 'support_ticket_resolved',
                'category' => 'chat',
                'priority' => 'medium',
                'title' => '✅ Issue Resolved',
                'title_ar' => '✅ تم حل المشكلة',
                'message' => 'Your support ticket #{ticket_number} has been resolved.',
                'message_ar' => 'تم حل تذكرتك رقم #{ticket_number}.',
                'icon' => '✅',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['ticket_number', 'complaint_id']),
            ],
            [
                'code' => 'chat_closed',
                'category' => 'chat',
                'priority' => 'low',
                'title' => '📋 Chat Closed',
                'title_ar' => '📋 تم إغلاق المحادثة',
                'message' => 'Your support chat #{ticket_number} has been closed.',
                'message_ar' => 'تم إغلاق محادثة الدعم رقم #{ticket_number}.',
                'icon' => '📋',
                'default_action_target' => '/complaints/{complaint_id}',
                'variables' => json_encode(['ticket_number', 'complaint_id']),
            ],

            // ==================== ACCOUNT & SECURITY (10 types) ====================
            [
                'code' => 'new_login_detected',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 New Login Detected',
                'title_ar' => '🔐 تم اكتشاف تسجيل دخول جديد',
                'message' => 'New login from {device} at {location}.',
                'message_ar' => 'تسجيل دخول جديد من {device} في {location}.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['device', 'location', 'time', 'ip']),
            ],
            [
                'code' => 'new_device_login',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 Login from New Device',
                'title_ar' => '🔐 تسجيل دخول من جهاز جديد',
                'message' => 'Your account was accessed from a new {device_type}.',
                'message_ar' => 'تم الوصول لحسابك من {device_type} جديد.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['device_type', 'device_name', 'location']),
            ],
            [
                'code' => 'password_changed',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 Password Changed',
                'title_ar' => '🔐 تم تغيير كلمة المرور',
                'message' => 'Your password was changed. If not you, contact support.',
                'message_ar' => 'تم تغيير كلمة مرورك. إذا لم تكن أنت، تواصل مع الدعم.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'password_reset_requested',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 Password Reset Requested',
                'title_ar' => '🔐 طلب إعادة تعيين كلمة المرور',
                'message' => 'A password reset was requested for your account.',
                'message_ar' => 'تم طلب إعادة تعيين كلمة المرور لحسابك.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'email_changed',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 Email Changed',
                'title_ar' => '🔐 تم تغيير البريد الإلكتروني',
                'message' => 'Your email was changed to {new_email}.',
                'message_ar' => 'تم تغيير بريدك الإلكتروني إلى {new_email}.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['new_email']),
            ],
            [
                'code' => 'phone_changed',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🔐 Phone Number Changed',
                'title_ar' => '🔐 تم تغيير رقم الهاتف',
                'message' => 'Your phone number was changed to {new_phone}.',
                'message_ar' => 'تم تغيير رقم هاتفك إلى {new_phone}.',
                'icon' => '🔐',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['new_phone']),
            ],
            [
                'code' => 'suspicious_activity',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🚫 Suspicious Activity Detected',
                'title_ar' => '🚫 تم اكتشاف نشاط مشبوه',
                'message' => 'Unusual activity detected on your account. Please verify.',
                'message_ar' => 'تم اكتشاف نشاط غير عادي. يرجى التحقق.',
                'icon' => '🚫',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['activity_type', 'location']),
            ],
            [
                'code' => 'account_locked',
                'category' => 'account',
                'priority' => 'critical',
                'title' => '🚫 Account Temporarily Locked',
                'title_ar' => '🚫 تم قفل الحساب مؤقتاً',
                'message' => 'Your account has been locked due to {reason}.',
                'message_ar' => 'تم قفل حسابك بسبب {reason}.',
                'icon' => '🚫',
                'default_action_target' => '/profile/security',
                'variables' => json_encode(['reason']),
            ],
            [
                'code' => 'account_verified',
                'category' => 'account',
                'priority' => 'high',
                'title' => '✅ Account Verified',
                'title_ar' => '✅ تم التحقق من الحساب',
                'message' => 'Your account has been successfully verified!',
                'message_ar' => 'تم التحقق من حسابك بنجاح!',
                'icon' => '✅',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'verification_failed',
                'category' => 'account',
                'priority' => 'high',
                'title' => '❌ Verification Failed',
                'title_ar' => '❌ فشل التحقق',
                'message' => 'Account verification failed. Please try again.',
                'message_ar' => 'فشل التحقق من الحساب. يرجى المحاولة مرة أخرى.',
                'icon' => '❌',
                'default_action_target' => '/profile',
                'variables' => json_encode(['reason']),
            ],

            // ==================== WALLET & PAYMENTS (7 types) ====================
            [
                'code' => 'wallet_credited',
                'category' => 'wallet',
                'priority' => 'high',
                'title' => '💰 Wallet Credited',
                'title_ar' => '💰 تم شحن المحفظة',
                'message' => '{amount} EGP added to your wallet. Balance: {balance} EGP',
                'message_ar' => 'تم إضافة {amount} جنيه. الرصيد: {balance} جنيه',
                'icon' => '💰',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['amount', 'balance', 'reference']),
            ],
            [
                'code' => 'wallet_debited',
                'category' => 'wallet',
                'priority' => 'high',
                'title' => '💸 Wallet Debited',
                'title_ar' => '💸 تم الخصم من المحفظة',
                'message' => '{amount} EGP used from wallet. Balance: {balance} EGP',
                'message_ar' => 'تم استخدام {amount} جنيه. الرصيد: {balance} جنيه',
                'icon' => '💸',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['amount', 'balance', 'reference']),
            ],
            [
                'code' => 'cashback_received',
                'category' => 'wallet',
                'priority' => 'medium',
                'title' => '🧾 Cashback Received!',
                'title_ar' => '🧾 حصلت على كاش باك!',
                'message' => 'You received {amount} EGP cashback from order #{order_number}!',
                'message_ar' => 'حصلت على {amount} جنيه كاش باك من الطلب #{order_number}!',
                'icon' => '🧾',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['amount', 'order_number']),
            ],
            [
                'code' => 'cashback_expiring',
                'category' => 'wallet',
                'priority' => 'high',
                'title' => '🧾 Cashback Expiring!',
                'title_ar' => '🧾 الكاش باك على وشك الانتهاء!',
                'message' => '{amount} EGP cashback expires in {days} days. Use it now!',
                'message_ar' => '{amount} جنيه كاش باك ينتهي خلال {days} أيام. استخدمه الآن!',
                'icon' => '🧾',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['amount', 'days']),
            ],
            [
                'code' => 'low_wallet_balance',
                'category' => 'wallet',
                'priority' => 'low',
                'title' => '⚠️ Low Wallet Balance',
                'title_ar' => '⚠️ رصيد المحفظة منخفض',
                'message' => 'Your wallet balance is {balance} EGP. Top up now!',
                'message_ar' => 'رصيد محفظتك {balance} جنيه. اشحنها الآن!',
                'icon' => '⚠️',
                'default_action_target' => '/profile/wallet',
                'variables' => json_encode(['balance']),
            ],
            [
                'code' => 'card_added',
                'category' => 'wallet',
                'priority' => 'medium',
                'title' => '💳 Card Added',
                'title_ar' => '💳 تم إضافة البطاقة',
                'message' => 'Card ending in {last4} has been added to your account.',
                'message_ar' => 'تم إضافة البطاقة المنتهية بـ {last4} لحسابك.',
                'icon' => '💳',
                'default_action_target' => '/profile/payment-methods',
                'variables' => json_encode(['last4', 'card_type']),
            ],
            [
                'code' => 'card_removed',
                'category' => 'wallet',
                'priority' => 'medium',
                'title' => '💳 Card Removed',
                'title_ar' => '💳 تم حذف البطاقة',
                'message' => 'Card ending in {last4} has been removed from your account.',
                'message_ar' => 'تم حذف البطاقة المنتهية بـ {last4} من حسابك.',
                'icon' => '💳',
                'default_action_target' => '/profile/payment-methods',
                'variables' => json_encode(['last4']),
            ],

            // ==================== ADDRESS (4 types) ====================
            [
                'code' => 'address_added',
                'category' => 'address',
                'priority' => 'low',
                'title' => '🏠 Address Added',
                'title_ar' => '🏠 تم إضافة العنوان',
                'message' => 'New address "{label}" has been added.',
                'message_ar' => 'تم إضافة العنوان "{label}".',
                'icon' => '🏠',
                'default_action_target' => '/profile/addresses',
                'variables' => json_encode(['label', 'address_id']),
            ],
            [
                'code' => 'delivery_area_unavailable',
                'category' => 'address',
                'priority' => 'high',
                'title' => '📍 Delivery Not Available',
                'title_ar' => '📍 التوصيل غير متاح',
                'message' => 'Sorry, we don\'t deliver to {area} yet.',
                'message_ar' => 'عذراً، لا نوصل إلى {area} حالياً.',
                'icon' => '📍',
                'default_action_target' => '/profile/addresses',
                'variables' => json_encode(['area']),
            ],
            [
                'code' => 'delivery_area_available',
                'category' => 'address',
                'priority' => 'medium',
                'title' => '📍 Now Delivering to Your Area!',
                'title_ar' => '📍 نوصل لمنطقتك الآن!',
                'message' => 'Great news! We now deliver to {area}.',
                'message_ar' => 'أخبار رائعة! نوصل الآن إلى {area}.',
                'icon' => '📍',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode(['area']),
            ],
            [
                'code' => 'service_unavailable_location',
                'category' => 'address',
                'priority' => 'high',
                'title' => '🛑 Service Temporarily Unavailable',
                'title_ar' => '🛑 الخدمة غير متاحة مؤقتاً',
                'message' => 'Service is temporarily unavailable in {area}.',
                'message_ar' => 'الخدمة غير متاحة مؤقتاً في {area}.',
                'icon' => '🛑',
                'default_action_target' => '/profile/addresses',
                'variables' => json_encode(['area', 'reason']),
            ],

            // ==================== SYSTEM & POLICY (9 types) ====================
            [
                'code' => 'terms_updated',
                'category' => 'system',
                'priority' => 'high',
                'title' => '⚖️ Terms & Conditions Updated',
                'title_ar' => '⚖️ تم تحديث الشروط والأحكام',
                'message' => 'Our Terms & Conditions have been updated. Please review.',
                'message_ar' => 'تم تحديث الشروط والأحكام. يرجى المراجعة.',
                'icon' => '⚖️',
                'default_action_target' => '/terms',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'privacy_updated',
                'category' => 'system',
                'priority' => 'high',
                'title' => '🔒 Privacy Policy Updated',
                'title_ar' => '🔒 تم تحديث سياسة الخصوصية',
                'message' => 'Our Privacy Policy has been updated. Please review.',
                'message_ar' => 'تم تحديث سياسة الخصوصية. يرجى المراجعة.',
                'icon' => '🔒',
                'default_action_target' => '/privacy',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'refund_policy_updated',
                'category' => 'system',
                'priority' => 'medium',
                'title' => '📜 Refund Policy Updated',
                'title_ar' => '📜 تم تحديث سياسة الاسترداد',
                'message' => 'Our refund policy has been updated.',
                'message_ar' => 'تم تحديث سياسة الاسترداد.',
                'icon' => '📜',
                'default_action_target' => '/refund-policy',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'app_update_available',
                'category' => 'system',
                'priority' => 'medium',
                'title' => '🆕 App Update Available',
                'title_ar' => '🆕 تحديث التطبيق متاح',
                'message' => 'Version {version} is available with new features!',
                'message_ar' => 'الإصدار {version} متاح بميزات جديدة!',
                'icon' => '🆕',
                'default_action_target' => '/app-store',
                'variables' => json_encode(['version', 'features']),
            ],
            [
                'code' => 'app_update_required',
                'category' => 'system',
                'priority' => 'critical',
                'title' => '🚨 Update Required',
                'title_ar' => '🚨 التحديث مطلوب',
                'message' => 'Please update to version {version} to continue using the app.',
                'message_ar' => 'يرجى التحديث للإصدار {version} لمتابعة استخدام التطبيق.',
                'icon' => '🚨',
                'default_action_target' => '/app-store',
                'variables' => json_encode(['version']),
            ],
            [
                'code' => 'service_outage',
                'category' => 'system',
                'priority' => 'critical',
                'title' => '🚨 Service Outage',
                'title_ar' => '🚨 انقطاع الخدمة',
                'message' => 'We\'re experiencing issues. We\'re working on it!',
                'message_ar' => 'نواجه مشكلات تقنية. نعمل على حلها!',
                'icon' => '🚨',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode(['affected_services']),
            ],
            [
                'code' => 'maintenance_scheduled',
                'category' => 'system',
                'priority' => 'high',
                'title' => '🚨 Scheduled Maintenance',
                'title_ar' => '🚨 صيانة مجدولة',
                'message' => 'Maintenance scheduled on {date} from {start} to {end}.',
                'message_ar' => 'صيانة مجدولة يوم {date} من {start} إلى {end}.',
                'icon' => '🚨',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode(['date', 'start', 'end']),
            ],
            [
                'code' => 'maintenance_completed',
                'category' => 'system',
                'priority' => 'medium',
                'title' => '✅ Maintenance Completed',
                'title_ar' => '✅ اكتملت الصيانة',
                'message' => 'Maintenance is complete. Everything is back to normal!',
                'message_ar' => 'اكتملت الصيانة. كل شيء يعمل بشكل طبيعي!',
                'icon' => '✅',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode([]),
            ],
            [
                'code' => 'legal_notice',
                'category' => 'system',
                'priority' => 'critical',
                'title' => '🚨 Important Notice',
                'title_ar' => '🚨 إشعار هام',
                'message' => '{notice_title}: {notice_message}',
                'message_ar' => '{notice_title}: {notice_message}',
                'icon' => '🚨',
                'default_action_target' => '/notices/{notice_id}',
                'variables' => json_encode(['notice_title', 'notice_message', 'notice_id']),
            ],

            // ==================== SMART / AI (6 types) ====================
            [
                'code' => 'reorder_reminder',
                'category' => 'smart',
                'priority' => 'low',
                'title' => '⏰ Time to Reorder',
                'title_ar' => '⏰ حان وقت إعادة الطلب',
                'message' => 'Running low on {product_name}? Reorder now!',
                'message_ar' => '{product_name} على وشك النفاذ؟ اطلبه الآن!',
                'icon' => '⏰',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'last_ordered']),
            ],
            [
                'code' => 'usually_buy_offer',
                'category' => 'smart',
                'priority' => 'medium',
                'title' => '🛒 Your Favorite is On Sale!',
                'title_ar' => '🛒 منتجك المفضل في خصم!',
                'message' => '{product_name} you usually buy is now {discount}% off!',
                'message_ar' => '{product_name} الذي تشتريه عادة الآن بخصم {discount}%!',
                'icon' => '🛒',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'discount']),
            ],
            [
                'code' => 'forgot_something',
                'category' => 'smart',
                'priority' => 'low',
                'title' => '🧾 Forgot Something?',
                'title_ar' => '🧾 نسيت شيئاً؟',
                'message' => 'Based on your order, you might need {product_name}.',
                'message_ar' => 'بناءً على طلبك، قد تحتاج {product_name}.',
                'icon' => '🧾',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'reorder_previous',
                'category' => 'smart',
                'priority' => 'low',
                'title' => '🔁 Reorder Your Last Order?',
                'title_ar' => '🔁 إعادة طلبك السابق؟',
                'message' => 'Want to reorder your order from {date}?',
                'message_ar' => 'هل تريد إعادة طلبك من {date}؟',
                'icon' => '🔁',
                'default_action_target' => '/orders/{order_id}',
                'variables' => json_encode(['order_id', 'date', 'total']),
            ],
            [
                'code' => 'recommended_for_you',
                'category' => 'smart',
                'priority' => 'low',
                'title' => '🧠 Recommended for You',
                'title_ar' => '🧠 موصى به لك',
                'message' => 'Based on your purchases: {product_name}',
                'message_ar' => 'بناءً على مشترياتك: {product_name}',
                'icon' => '🧠',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id']),
            ],
            [
                'code' => 'similar_cheaper',
                'category' => 'smart',
                'priority' => 'low',
                'title' => '🛍️ Similar Item, Better Price',
                'title_ar' => '🛍️ منتج مشابه بسعر أفضل',
                'message' => '{product_name} is similar to what you bought, but cheaper!',
                'message_ar' => '{product_name} مشابه لما اشتريته، لكن أرخص!',
                'icon' => '🛍️',
                'default_action_target' => '/product/{product_id}',
                'variables' => json_encode(['product_name', 'product_id', 'price']),
            ],

            // ==================== WELCOME & ACCOUNT ====================
            [
                'code' => 'welcome',
                'category' => 'account',
                'priority' => 'medium',
                'title' => '👋 Welcome to CART!',
                'title_ar' => '👋 أهلاً بك في CART!',
                'message' => 'Hi {name}! Explore fresh products and amazing deals.',
                'message_ar' => 'مرحباً {name}! استكشف منتجاتنا الطازجة وعروضنا الرائعة.',
                'icon' => '👋',
                'default_action_target' => '/(tabs)/home',
                'variables' => json_encode(['name']),
            ],
        ];

        foreach ($templates as $template) {
            DB::table('notification_templates')->updateOrInsert(
                ['code' => $template['code']],
                array_merge($template, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
